/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OptionCalculator: typeof import('./src/components/OptionCalculator.vue')['default']
    OptionPnLChart: typeof import('./src/components/OptionPnLChart.vue')['default']
    OptionTable: typeof import('./src/components/OptionTable.vue')['default']
    Reference: typeof import('./src/components/Reference.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
