name: Node.js Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: get-project-version
      run: Add-Content -Path ${env:GITHUB_ENV} -Value "PACKAGE_VERSION=$(npm pkg get version | sed 's/"//g')"
    - name: Packaging for windows platform
      run: npm run package_win
    - name: Release Windows EXE
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/option-toolbox-${{ env.PACKAGE_VERSION }}-*.exe
        file_glob: true
        overwrite: true
        body: Version - ${{ env.PACKAGE_VERSION }}
